"""add_marketplace_scripts_table

Revision ID: 0002_marketplace
Revises: 0001_max_concurrent_exec
Create Date: 2025-09-12 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002_marketplace'
down_revision = '0001_max_concurrent_exec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('script_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_scripts_id'), 'marketplace_scripts', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_scripts_name'), 'marketplace_scripts', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_scripts_name'), table_name='marketplace_scripts')
    op.drop_index(op.f('ix_marketplace_scripts_id'), table_name='marketplace_scripts')
    op.drop_table('marketplace_scripts')
    # ### end Alembic commands ###
